//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wkiro.ImageClassification.Gui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataProviderConfiguration_TrainFilesLocationPath {
            get {
                return ((string)(this["DataProviderConfiguration_TrainFilesLocationPath"]));
            }
            set {
                this["DataProviderConfiguration_TrainFilesLocationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jpg;png;bmp")]
        public string DataProviderConfiguration_FileExtensions {
            get {
                return ((string)(this["DataProviderConfiguration_FileExtensions"]));
            }
            set {
                this["DataProviderConfiguration_FileExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500; 300; 100")]
        public string GlobalTrainerConfiguration_HiddenLayers {
            get {
                return ((string)(this["GlobalTrainerConfiguration_HiddenLayers"]));
            }
            set {
                this["GlobalTrainerConfiguration_HiddenLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DataProviderConfiguration_ProcessingWidth {
            get {
                return ((int)(this["DataProviderConfiguration_ProcessingWidth"]));
            }
            set {
                this["DataProviderConfiguration_ProcessingWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DataProviderConfiguration_ProcessingHeight {
            get {
                return ((int)(this["DataProviderConfiguration_ProcessingHeight"]));
            }
            set {
                this["DataProviderConfiguration_ProcessingHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double GlobalTrainerConfiguration_TrainDataRatio {
            get {
                return ((double)(this["GlobalTrainerConfiguration_TrainDataRatio"]));
            }
            set {
                this["GlobalTrainerConfiguration_TrainDataRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Training1Parameters_Momentum {
            get {
                return ((double)(this["Training1Parameters_Momentum"]));
            }
            set {
                this["Training1Parameters_Momentum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double Training1Parameters_Decay {
            get {
                return ((double)(this["Training1Parameters_Decay"]));
            }
            set {
                this["Training1Parameters_Decay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Training1Parameters_LearningRate {
            get {
                return ((double)(this["Training1Parameters_LearningRate"]));
            }
            set {
                this["Training1Parameters_LearningRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Training1Parameters_UnsupervisedEpochs {
            get {
                return ((int)(this["Training1Parameters_UnsupervisedEpochs"]));
            }
            set {
                this["Training1Parameters_UnsupervisedEpochs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Training2Parameters_Momentum {
            get {
                return ((double)(this["Training2Parameters_Momentum"]));
            }
            set {
                this["Training2Parameters_Momentum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double Training2Parameters_LearningRate {
            get {
                return ((double)(this["Training2Parameters_LearningRate"]));
            }
            set {
                this["Training2Parameters_LearningRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Training2Parameters_SupervisedEpochs {
            get {
                return ((int)(this["Training2Parameters_SupervisedEpochs"]));
            }
            set {
                this["Training2Parameters_SupervisedEpochs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DataProviderConfiguration_UseGrayScale {
            get {
                return ((bool)(this["DataProviderConfiguration_UseGrayScale"]));
            }
            set {
                this["DataProviderConfiguration_UseGrayScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataProviderConfiguration_ShouldAutoCrop {
            get {
                return ((bool)(this["DataProviderConfiguration_ShouldAutoCrop"]));
            }
            set {
                this["DataProviderConfiguration_ShouldAutoCrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DataProviderConfiguration_ShouldEqualizeHistogram {
            get {
                return ((bool)(this["DataProviderConfiguration_ShouldEqualizeHistogram"]));
            }
            set {
                this["DataProviderConfiguration_ShouldEqualizeHistogram"] = value;
            }
        }
    }
}
